name: Make and Deploy Sphinx

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        python -m pip install -U pip
        python -m pip install -r requirements.txt black

    - name: Make
      run: |
        make html
